package com.example.buildingmanagementdemo.model;

import java.util.ArrayList;
import java.util.List;

public class AllocationHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public AllocationHistoryExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andAllocatedToIsNull() {
            addCriterion("allocated_to is null");
            return (Criteria) this;
        }

        public Criteria andAllocatedToIsNotNull() {
            addCriterion("allocated_to is not null");
            return (Criteria) this;
        }

        public Criteria andAllocatedToEqualTo(String value) {
            addCriterion("allocated_to =", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToNotEqualTo(String value) {
            addCriterion("allocated_to <>", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToGreaterThan(String value) {
            addCriterion("allocated_to >", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToGreaterThanOrEqualTo(String value) {
            addCriterion("allocated_to >=", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToLessThan(String value) {
            addCriterion("allocated_to <", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToLessThanOrEqualTo(String value) {
            addCriterion("allocated_to <=", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToLike(String value) {
            addCriterion("allocated_to like", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToNotLike(String value) {
            addCriterion("allocated_to not like", value, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToIn(List<String> values) {
            addCriterion("allocated_to in", values, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToNotIn(List<String> values) {
            addCriterion("allocated_to not in", values, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToBetween(String value1, String value2) {
            addCriterion("allocated_to between", value1, value2, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocatedToNotBetween(String value1, String value2) {
            addCriterion("allocated_to not between", value1, value2, "allocatedTo");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIsNull() {
            addCriterion("allocation_time is null");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIsNotNull() {
            addCriterion("allocation_time is not null");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeEqualTo(Long value) {
            addCriterion("allocation_time =", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotEqualTo(Long value) {
            addCriterion("allocation_time <>", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeGreaterThan(Long value) {
            addCriterion("allocation_time >", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("allocation_time >=", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeLessThan(Long value) {
            addCriterion("allocation_time <", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeLessThanOrEqualTo(Long value) {
            addCriterion("allocation_time <=", value, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeIn(List<Long> values) {
            addCriterion("allocation_time in", values, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotIn(List<Long> values) {
            addCriterion("allocation_time not in", values, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeBetween(Long value1, Long value2) {
            addCriterion("allocation_time between", value1, value2, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andAllocationTimeNotBetween(Long value1, Long value2) {
            addCriterion("allocation_time not between", value1, value2, "allocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeIsNull() {
            addCriterion("deallocation_time is null");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeIsNotNull() {
            addCriterion("deallocation_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeEqualTo(Long value) {
            addCriterion("deallocation_time =", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeNotEqualTo(Long value) {
            addCriterion("deallocation_time <>", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeGreaterThan(Long value) {
            addCriterion("deallocation_time >", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("deallocation_time >=", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeLessThan(Long value) {
            addCriterion("deallocation_time <", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeLessThanOrEqualTo(Long value) {
            addCriterion("deallocation_time <=", value, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeIn(List<Long> values) {
            addCriterion("deallocation_time in", values, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeNotIn(List<Long> values) {
            addCriterion("deallocation_time not in", values, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeBetween(Long value1, Long value2) {
            addCriterion("deallocation_time between", value1, value2, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andDeallocationTimeNotBetween(Long value1, Long value2) {
            addCriterion("deallocation_time not between", value1, value2, "deallocationTime");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("notes =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("notes <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("notes >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("notes >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("notes <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("notes <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("notes not between", value1, value2, "notes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table allocation_history
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 14 12:52:55 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table allocation_history
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}