package com.example.buildingmanagementdemo.model;

import java.util.Date;

public class AllocationHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.room_id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.allocated_to
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private String allocatedTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.allocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private Date allocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.deallocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private Date deallocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocation_history.notes
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.id
     *
     * @return the value of allocation_history.id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.id
     *
     * @param id the value for allocation_history.id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.room_id
     *
     * @return the value of allocation_history.room_id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.room_id
     *
     * @param roomId the value for allocation_history.room_id
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.allocated_to
     *
     * @return the value of allocation_history.allocated_to
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public String getAllocatedTo() {
        return allocatedTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.allocated_to
     *
     * @param allocatedTo the value for allocation_history.allocated_to
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setAllocatedTo(String allocatedTo) {
        this.allocatedTo = allocatedTo == null ? null : allocatedTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.allocation_time
     *
     * @return the value of allocation_history.allocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public Date getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.allocation_time
     *
     * @param allocationTime the value for allocation_history.allocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setAllocationTime(Date allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.deallocation_time
     *
     * @return the value of allocation_history.deallocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public Date getDeallocationTime() {
        return deallocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.deallocation_time
     *
     * @param deallocationTime the value for allocation_history.deallocation_time
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setDeallocationTime(Date deallocationTime) {
        this.deallocationTime = deallocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocation_history.notes
     *
     * @return the value of allocation_history.notes
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocation_history.notes
     *
     * @param notes the value for allocation_history.notes
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}