package com.example.buildingmanagementdemo.model;

public class Allocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.room_id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.allocated_to
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private String allocatedTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.allocation_time
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private Long allocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.status
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column allocations.notes
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.id
     *
     * @return the value of allocations.id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.id
     *
     * @param id the value for allocations.id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.room_id
     *
     * @return the value of allocations.room_id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.room_id
     *
     * @param roomId the value for allocations.room_id
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.allocated_to
     *
     * @return the value of allocations.allocated_to
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public String getAllocatedTo() {
        return allocatedTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.allocated_to
     *
     * @param allocatedTo the value for allocations.allocated_to
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setAllocatedTo(String allocatedTo) {
        this.allocatedTo = allocatedTo == null ? null : allocatedTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.allocation_time
     *
     * @return the value of allocations.allocation_time
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Long getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.allocation_time
     *
     * @param allocationTime the value for allocations.allocation_time
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setAllocationTime(Long allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.status
     *
     * @return the value of allocations.status
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.status
     *
     * @param status the value for allocations.status
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column allocations.notes
     *
     * @return the value of allocations.notes
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column allocations.notes
     *
     * @param notes the value for allocations.notes
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}