package com.example.buildingmanagementdemo.mapper;

import com.example.buildingmanagementdemo.model.Allocations;
import com.example.buildingmanagementdemo.model.AllocationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllocationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    long countByExample(AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByExample(AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insert(Allocations row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insertSelective(Allocations row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    List<Allocations> selectByExampleWithBLOBs(AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    List<Allocations> selectByExample(AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    Allocations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExampleSelective(@Param("row") Allocations row, @Param("example") AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Allocations row, @Param("example") AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExample(@Param("row") Allocations row, @Param("example") AllocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKeySelective(Allocations row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Allocations row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKey(Allocations row);
}