package com.example.buildingmanagementdemo.mapper;

import com.example.buildingmanagementdemo.model.AllocationHistory;
import com.example.buildingmanagementdemo.model.AllocationHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllocationHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    long countByExample(AllocationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByExample(AllocationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insert(AllocationHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insertSelective(AllocationHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    List<AllocationHistory> selectByExample(AllocationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    AllocationHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExampleSelective(@Param("row") AllocationHistory row, @Param("example") AllocationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExample(@Param("row") AllocationHistory row, @Param("example") AllocationHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKeySelective(AllocationHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocation_history
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKey(AllocationHistory row);
}