package com.example.buildingmanagementdemo.mapper;

import com.example.buildingmanagementdemo.model.Allocation;
import com.example.buildingmanagementdemo.model.AllocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    long countByExample(AllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int deleteByExample(AllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int insert(Allocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int insertSelective(Allocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    List<Allocation> selectByExample(AllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    Allocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int updateByExampleSelective(@Param("row") Allocation row, @Param("example") AllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int updateByExample(@Param("row") Allocation row, @Param("example") AllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int updateByPrimaryKeySelective(Allocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table allocations
     *
     * @mbg.generated Sun Jul 14 12:52:55 CST 2024
     */
    int updateByPrimaryKey(Allocation row);
}