package com.example.buildingmanagementdemo.mapper;

import com.example.buildingmanagementdemo.model.Building;
import com.example.buildingmanagementdemo.model.BuildingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    long countByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insert(Building row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int insertSelective(Building row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    List<Building> selectByExample(BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    Building selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExampleSelective(@Param("row") Building row, @Param("example") BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByExample(@Param("row") Building row, @Param("example") BuildingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKeySelective(Building row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Sat Jul 13 14:41:29 CST 2024
     */
    int updateByPrimaryKey(Building row);
}